AUGMENTATION: True
IMAGE_SIZE: [224,224,3] #as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2 # Dog and Cat
WEIGHTS: imagenet #weights from pre-trained on imagenet dataset. weights already on tensorflow dataset. (transfer learning)
LEARNING_RATE: 0.01